# Generated by Django 2.1 on 2018-08-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls_app', '0004_auto_20180830_2209'),
        ('count_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invcount',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invcount', to='controls_app.Control'),
        ),
    ]
