# Generated by Django 2.1 on 2018-09-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0008_auto_20180829_2201'),
        ('count_app', '0002_invcount_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='invcount',
            name='mainlocation',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='invcount', to='location_app.MainLocation'),
            preserve_default=False,
        ),
    ]
