# Generated by Django 2.1 on 2018-09-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_auto_20180901_2107'),
        ('count_app', '0003_invcount_mainlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invcount',
            name='inventorytype',
        ),
        migrations.RemoveField(
            model_name='invcount',
            name='mainlocation',
        ),
        migrations.AddField(
            model_name='invcount',
            name='inventorytypemainlocation',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='invcount', to='inventory_app.InventoryTypeMainLocation'),
            preserve_default=False,
        ),
    ]
