# Generated by Django 2.0.7 on 2018-08-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('engagement', models.ForeignKey(on_delete='Cascade', related_name='mainlocation', to='engagement_app.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='TypeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('engagement', models.ForeignKey(on_delete='Cascade', related_name='typelocation', to='engagement_app.Engagement')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='typelocation',
            unique_together={('type', 'engagement')},
        ),
        migrations.AlterUniqueTogether(
            name='mainlocation',
            unique_together={('name', 'engagement')},
        ),
    ]
