# Generated by Django 2.0.7 on 2018-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_mainlocationinfo_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub1Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mainlocation', models.ForeignKey(on_delete='Cascade', related_name='sub1location', to='location_app.MainLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Sub1LocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1location', models.ForeignKey(blank=True, on_delete='Cascade', related_name='sub1locationinfo', to='location_app.Sub1Location')),
                ('type', models.ForeignKey(blank=True, on_delete='Cascade', related_name='sub1locationinfotype', to='location_app.TypeLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Sub2Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sub1location', models.ForeignKey(on_delete='Cascade', related_name='sub2location', to='location_app.MainLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Sub2LocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub2location', models.ForeignKey(blank=True, on_delete='Cascade', related_name='sub2locationinfo', to='location_app.Sub2Location')),
                ('type', models.ForeignKey(blank=True, on_delete='Cascade', related_name='sub2locationinfotype', to='location_app.TypeLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Sub3Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sub2location', models.ForeignKey(on_delete='Cascade', related_name='sub3location', to='location_app.MainLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Sub3LocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub3location', models.ForeignKey(blank=True, on_delete='Cascade', related_name='sub3locationinfo', to='location_app.Sub3Location')),
                ('type', models.ForeignKey(blank=True, on_delete='Cascade', related_name='sub3locationinfotype', to='location_app.TypeLocation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sub3locationinfo',
            unique_together={('type', 'sub3location')},
        ),
        migrations.AlterUniqueTogether(
            name='sub3location',
            unique_together={('name', 'sub2location')},
        ),
        migrations.AlterUniqueTogether(
            name='sub2locationinfo',
            unique_together={('type', 'sub2location')},
        ),
        migrations.AlterUniqueTogether(
            name='sub2location',
            unique_together={('name', 'sub1location')},
        ),
        migrations.AlterUniqueTogether(
            name='sub1locationinfo',
            unique_together={('type', 'sub1location')},
        ),
        migrations.AlterUniqueTogether(
            name='sub1location',
            unique_together={('name', 'mainlocation')},
        ),
    ]
