# Generated by Django 2.0.7 on 2018-08-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0004_auto_20180818_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mainlocation', models.ForeignKey(on_delete='Cascade', related_name='subonelocation', to='location_app.MainLocation')),
            ],
        ),
        migrations.CreateModel(
            name='SubOneLocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subonelocation', models.ForeignKey(blank=True, on_delete='Cascade', related_name='subonelocationinfo', to='location_app.SubOneLocation')),
                ('type', models.ForeignKey(blank=True, on_delete='Cascade', related_name='subonelocationinfotype', to='location_app.TypeLocation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sub1location',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sub1location',
            name='mainlocation',
        ),
        migrations.AlterUniqueTogether(
            name='sub1locationinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sub1locationinfo',
            name='sub1location',
        ),
        migrations.RemoveField(
            model_name='sub1locationinfo',
            name='type',
        ),
        migrations.AlterField(
            model_name='sub2location',
            name='sub1location',
            field=models.ForeignKey(on_delete='Cascade', related_name='sub2location', to='location_app.SubOneLocation'),
        ),
        migrations.AlterField(
            model_name='sub3location',
            name='sub2location',
            field=models.ForeignKey(on_delete='Cascade', related_name='sub3location', to='location_app.Sub2Location'),
        ),
        migrations.DeleteModel(
            name='Sub1Location',
        ),
        migrations.DeleteModel(
            name='Sub1LocationInfo',
        ),
        migrations.AlterUniqueTogether(
            name='subonelocationinfo',
            unique_together={('type', 'subonelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='subonelocation',
            unique_together={('name', 'mainlocation')},
        ),
    ]
