# Generated by Django 2.0.7 on 2018-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0005_auto_20180818_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubThreeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubThreeLocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subthreelocation', models.ForeignKey(blank=True, on_delete='Cascade', related_name='subthreelocationinfo', to='location_app.SubThreeLocation')),
                ('type', models.ForeignKey(blank=True, on_delete='Cascade', related_name='subthreelocationinfotype', to='location_app.TypeLocation')),
            ],
        ),
        migrations.CreateModel(
            name='SubTwoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subonelocation', models.ForeignKey(on_delete='Cascade', related_name='subtwolocation', to='location_app.SubOneLocation')),
            ],
        ),
        migrations.CreateModel(
            name='SubTwoLocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtwolocation', models.ForeignKey(blank=True, on_delete='Cascade', related_name='subtwolocationinfo', to='location_app.SubTwoLocation')),
                ('type', models.ForeignKey(blank=True, on_delete='Cascade', related_name='subtwolocationinfotype', to='location_app.TypeLocation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sub2location',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sub2location',
            name='sub1location',
        ),
        migrations.AlterUniqueTogether(
            name='sub2locationinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sub2locationinfo',
            name='sub2location',
        ),
        migrations.RemoveField(
            model_name='sub2locationinfo',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='sub3location',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sub3location',
            name='sub2location',
        ),
        migrations.AlterUniqueTogether(
            name='sub3locationinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sub3locationinfo',
            name='sub3location',
        ),
        migrations.RemoveField(
            model_name='sub3locationinfo',
            name='type',
        ),
        migrations.DeleteModel(
            name='Sub2Location',
        ),
        migrations.DeleteModel(
            name='Sub2LocationInfo',
        ),
        migrations.DeleteModel(
            name='Sub3Location',
        ),
        migrations.DeleteModel(
            name='Sub3LocationInfo',
        ),
        migrations.AddField(
            model_name='subthreelocation',
            name='subtwolocation',
            field=models.ForeignKey(on_delete='Cascade', related_name='subthreelocation', to='location_app.SubTwoLocation'),
        ),
        migrations.AlterUniqueTogether(
            name='subtwolocationinfo',
            unique_together={('type', 'subtwolocation')},
        ),
        migrations.AlterUniqueTogether(
            name='subtwolocation',
            unique_together={('name', 'subonelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='subthreelocationinfo',
            unique_together={('type', 'subthreelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='subthreelocation',
            unique_together={('name', 'subtwolocation')},
        ),
    ]
