# Generated by Django 2.1 on 2018-08-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0006_auto_20180818_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlocation',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainlocation', to='engagement_app.Engagement'),
        ),
        migrations.AlterField(
            model_name='mainlocationinfo',
            name='mainlocation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainlocationinfo', to='location_app.MainLocation'),
        ),
        migrations.AlterField(
            model_name='mainlocationinfo',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainlocationinfotype', to='location_app.TypeLocation'),
        ),
        migrations.AlterField(
            model_name='subonelocation',
            name='mainlocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subonelocation', to='location_app.MainLocation'),
        ),
        migrations.AlterField(
            model_name='subonelocationinfo',
            name='subonelocation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subonelocationinfo', to='location_app.SubOneLocation'),
        ),
        migrations.AlterField(
            model_name='subonelocationinfo',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subonelocationinfotype', to='location_app.TypeLocation'),
        ),
        migrations.AlterField(
            model_name='subthreelocation',
            name='subtwolocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subthreelocation', to='location_app.SubTwoLocation'),
        ),
        migrations.AlterField(
            model_name='subthreelocationinfo',
            name='subthreelocation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthreelocationinfo', to='location_app.SubThreeLocation'),
        ),
        migrations.AlterField(
            model_name='subthreelocationinfo',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthreelocationinfotype', to='location_app.TypeLocation'),
        ),
        migrations.AlterField(
            model_name='subtwolocation',
            name='subonelocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtwolocation', to='location_app.SubOneLocation'),
        ),
        migrations.AlterField(
            model_name='subtwolocationinfo',
            name='subtwolocation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtwolocationinfo', to='location_app.SubTwoLocation'),
        ),
        migrations.AlterField(
            model_name='subtwolocationinfo',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtwolocationinfotype', to='location_app.TypeLocation'),
        ),
        migrations.AlterField(
            model_name='typelocation',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typelocation', to='engagement_app.Engagement'),
        ),
    ]
