# Generated by Django 2.1 on 2018-08-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement_app', '0007_auto_20180829_1249'),
        ('inventory_app', '0003_auto_20180826_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('blindcount', models.BooleanField()),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='engagement_app.Engagement')),
                ('inventorytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='inventory_app.InventoryType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('ref', 'engagement')},
        ),
    ]
