# Generated by Django 2.1 on 2018-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='blindcount',
        ),
        migrations.RemoveField(
            model_name='control',
            name='date',
        ),
        migrations.RemoveField(
            model_name='control',
            name='inventorytype',
        ),
        migrations.AddField(
            model_name='control',
            name='configurable',
            field=models.BooleanField(help_text='Is this control configurable?', null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='control_type',
            field=models.CharField(choices=[('IT APP Control', 'IT APP Control'), ('ITDM Control', 'ITDM Control'), ('Manual Prevent', 'Manual Prevent'), ('Manual Detect', 'Manual Detect')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='frequency',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('On Occurance', 'On Occurance'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
