# Generated by Django 2.1 on 2018-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls_app', '0002_auto_20180829_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['ref']},
        ),
        migrations.AddField(
            model_name='control',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
