# Generated by Django 2.1 on 2018-08-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0008_auto_20180829_2201'),
        ('inventory_app', '0004_auto_20180829_2201'),
        ('controls_app', '0003_auto_20180829_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryClassControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasscontrol', to='controls_app.Control')),
                ('inventoryclass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasscontrol', to='inventory_app.InventoryClass')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTypeControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypecontrol', to='controls_app.Control')),
                ('inventorytype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypecontrol', to='inventory_app.InventoryType')),
            ],
        ),
        migrations.CreateModel(
            name='MainLocationControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainlocationcontrol', to='controls_app.Control')),
                ('mainlocation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainlocationcontrol', to='location_app.MainLocation')),
            ],
        ),
        migrations.CreateModel(
            name='SubOneLocationControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subonelocationcontrol', to='controls_app.Control')),
                ('subonelocation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subonelocationcontrol', to='location_app.SubOneLocation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subonelocationcontrol',
            unique_together={('control', 'subonelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='mainlocationcontrol',
            unique_together={('control', 'mainlocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypecontrol',
            unique_together={('control', 'inventorytype')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasscontrol',
            unique_together={('control', 'inventoryclass')},
        ),
    ]
