# Generated by Django 2.1 on 2018-09-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls_app', '0004_auto_20180830_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='configurable',
            field=models.BooleanField(null=True),
        ),
    ]
