# Generated by Django 2.1 on 2018-08-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainlocation_name', models.CharField(default='Main Location', max_length=56, null=True)),
                ('subonelocation_name', models.CharField(default='Sub One Location', max_length=56, null=True)),
                ('subtwolocation_name', models.CharField(default='Sub Two Location', max_length=56, null=True)),
                ('subthreelocation_name', models.CharField(default='Sub Three Location', max_length=56, null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subonelocation', to='engagement_app.Engagement')),
            ],
        ),
    ]
