# Generated by Django 2.1 on 2018-08-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_app', '0002_locationnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationnames',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subonelocation', to='engagement_app.Engagement', unique=True),
        ),
    ]
