# Generated by Django 2.1 on 2018-08-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_app', '0005_auto_20180826_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationnames',
            name='id',
        ),
        migrations.AlterField(
            model_name='locationnames',
            name='engagement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='locationnames', serialize=False, to='engagement_app.Engagement'),
        ),
    ]
