# Generated by Django 2.1 on 2018-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_app', '0007_auto_20180829_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='location',
        ),
        migrations.AddField(
            model_name='engagement',
            name='industry',
            field=models.CharField(default='', max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engagement',
            name='office',
            field=models.CharField(default='', max_length=56),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='name',
            field=models.CharField(max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='partner',
            field=models.CharField(max_length=56),
        ),
    ]
