# Generated by Django 2.1 on 2018-08-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=56)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclass', to='engagement_app.Engagement')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('balance', models.IntegerField(null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytype', to='inventory_app.InventoryClass')),
            ],
        ),
        migrations.AddField(
            model_name='inventorysubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorysubtype', to='inventory_app.InventoryType'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorytype',
            unique_together={('name', 'classification')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorysubtype',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclass',
            unique_together={('classification', 'engagement')},
        ),
    ]
