# Generated by Django 2.1 on 2018-08-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0007_auto_20180819_1629'),
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryClassMainLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclassmainlocation', to='inventory_app.InventoryClass')),
                ('mainlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclassmainlocation', to='location_app.MainLocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryClassSubOneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasssubonelocation', to='inventory_app.InventoryClass')),
                ('subonelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasssubonelocation', to='location_app.SubOneLocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryClassSubThreeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasssubthreelocation', to='inventory_app.InventoryClass')),
                ('subthreelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasssubthreelocation', to='location_app.SubThreeLocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryClassSubTwoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasssubtwolocation', to='inventory_app.InventoryClass')),
                ('subtwolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryclasssubtwolocation', to='location_app.SubTwoLocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTypeMainLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('mainlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypemainlocation', to='location_app.MainLocation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypemainlocation', to='inventory_app.InventoryClass')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTypeSubOneLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('subonelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypesubonelocation', to='location_app.SubOneLocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTypeSubThreeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('subthreelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypesubthreelocation', to='location_app.SubThreeLocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTypeSubTwoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('subtwolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypesubtwolocation', to='location_app.SubTwoLocation')),
            ],
        ),
        migrations.AlterField(
            model_name='inventorysubtype',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytypesubtwolocation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypesubtwolocation', to='inventory_app.InventoryType'),
        ),
        migrations.AddField(
            model_name='inventorytypesubthreelocation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypesubthreelocation', to='inventory_app.InventoryType'),
        ),
        migrations.AddField(
            model_name='inventorytypesubonelocation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypesubonelocation', to='inventory_app.InventoryType'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypesubtwolocation',
            unique_together={('type', 'subtwolocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypesubthreelocation',
            unique_together={('type', 'subthreelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypesubonelocation',
            unique_together={('type', 'subonelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypemainlocation',
            unique_together={('type', 'mainlocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasssubtwolocation',
            unique_together={('classification', 'subtwolocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasssubthreelocation',
            unique_together={('classification', 'subthreelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasssubonelocation',
            unique_together={('classification', 'subonelocation')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclassmainlocation',
            unique_together={('classification', 'mainlocation')},
        ),
    ]
