# Generated by Django 2.1 on 2018-08-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20180825_1552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryclassmainlocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryclassmainlocation',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='inventoryclassmainlocation',
            name='mainlocation',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasssubonelocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryclasssubonelocation',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='inventoryclasssubonelocation',
            name='subonelocation',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasssubthreelocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryclasssubthreelocation',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='inventoryclasssubthreelocation',
            name='subthreelocation',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryclasssubtwolocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryclasssubtwolocation',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='inventoryclasssubtwolocation',
            name='subtwolocation',
        ),
        migrations.AlterField(
            model_name='inventorytypemainlocation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypemainlocation', to='inventory_app.InventoryType'),
        ),
        migrations.DeleteModel(
            name='InventoryClassMainLocation',
        ),
        migrations.DeleteModel(
            name='InventoryClassSubOneLocation',
        ),
        migrations.DeleteModel(
            name='InventoryClassSubThreeLocation',
        ),
        migrations.DeleteModel(
            name='InventoryClassSubTwoLocation',
        ),
    ]
