# Generated by Django 2.1 on 2018-09-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_auto_20180829_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytypemainlocation',
            name='cc_type',
            field=models.CharField(choices=[('Cycle Count', 'Cycle Count'), ('Full Physical', 'Full Physical'), ('Reliance on Third Party', 'Reliance on Third Party'), ('Other', 'Other'), ('N/A', 'N/A')], max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='inventorytypemainlocation',
            name='frequency',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Not Counted', 'Not Counted'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventorytypemainlocation',
            name='uom',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='inventorytypesubonelocation',
            name='cc_type',
            field=models.CharField(choices=[('Cycle Count', 'Cycle Count'), ('Full Physical', 'Full Physical'), ('Reliance on Third Party', 'Reliance on Third Party'), ('Other', 'Other'), ('N/A', 'N/A')], max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='inventorytypesubonelocation',
            name='frequency',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Not Counted', 'Not Counted'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventorytypesubonelocation',
            name='uom',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
