# Generated by Django 2.1 on 2018-08-31 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement_app', '0008_auto_20180829_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='', null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='engagement_app.Engagement')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='', null=True)),
                ('it_risk_1', models.TextField(default='', null=True)),
                ('it_risk_2', models.TextField(default='', null=True)),
                ('it_risk_3', models.TextField(default='', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='it_app.Application')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('name', 'engagement')},
        ),
    ]
