# Generated by Django 2.1 on 2018-08-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls_app', '0004_auto_20180830_2209'),
        ('it_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationControlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationcontrolinfo', to='it_app.Application')),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationcontrolinfo', to='controls_app.Control')),
            ],
        ),
        migrations.CreateModel(
            name='ReportControlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('control', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportcontrolinfo', to='controls_app.Control')),
                ('report', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportcontrolinfo', to='it_app.Report')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportcontrolinfo',
            unique_together={('report', 'control')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationcontrolinfo',
            unique_together={('application', 'control')},
        ),
    ]
