# Generated by Django 2.1 on 2018-09-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_auto_20180901_2107'),
        ('it_app', '0003_auto_20180904_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTypeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypeapplication', to='it_app.Application')),
                ('inventorytype', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorytypeapplication', to='inventory_app.InventoryType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inventorytypeapplication',
            unique_together={('application', 'inventorytype')},
        ),
    ]
